const mongoose = require('mongoose')
const dotenv = require('dotenv')
dotenv.config()

const Degree = require('./models/Degree')
const logger = require('./utils/logger')

const degrees = [
  // ══════════════════════════════════════════════════════════
  // ── 1. INTERMEDIATE & DIPLOMA TRACKS (For Matric / O-Level)
  // ══════════════════════════════════════════════════════════
  {
    name: 'FSc Pre-Engineering',
    shortName: 'FSC-ENG',
    level: 'intermediate',
    targetAudience: ['matric', 'olevel'],
    institutionType: 'Higher Secondary Colleges & Cadet Institutes',
    field: 'Engineering',
    description: 'Premier 2-year higher secondary science program focusing on Advanced Mathematics, Physics, and Chemistry. Foundation for all Engineering and Computing degrees.',
    duration: '2 years',
    requiredSubjects: ['Mathematics', 'Physics', 'Chemistry'],
    requiredStream: ['science', 'matric-science'],
    minGPA: 2.5,
    universities: [
      { name: 'Government College University (GCU)', location: 'Lahore', ranking: 1, feePerYear: 'PKR 45,000', hasScholarship: true, admissionTest: 'Matric Merit / BISE', website: 'https://gcu.edu.pk' },
      { name: 'Forman Christian College (FCCU)', location: 'Lahore', ranking: 2, feePerYear: 'PKR 120,000', hasScholarship: true, admissionTest: 'FCCU Entry Test', website: 'https://fccollege.edu.pk' },
      { name: 'Punjab Group of Colleges (PGC)', location: 'Nationwide (Lahore / Rwp / Isb)', ranking: 3, feePerYear: 'PKR 85,000', hasScholarship: true, admissionTest: 'Matric Marks Merit', website: 'https://pgc.edu' },
      { name: 'Cadet College Hasan Abdal', location: 'Hasan Abdal', ranking: 4, feePerYear: 'PKR 180,000', hasScholarship: true, admissionTest: 'Cadet College Test', website: 'https://cch.edu.pk' },
      { name: 'Islamia College Peshawar', location: 'Peshawar', ranking: 5, feePerYear: 'PKR 35,000', hasScholarship: true, admissionTest: 'BISE Merit', website: 'https://icp.edu.pk' },
    ],
    careerOutcomes: ['Pathway to BSEE / BSME / BSCE', 'Pathway to BS Computer Science / AI', 'Aviation / PAF Cadet Officer', 'Architecture & Robotics'],
    expectedSalary: 'Higher Studies Foundation (Leads to PKR 90k-350k/mo BS jobs)',
    jobMarket: 'excellent',
    idealInterestAreas: ['Engineering', 'Technology'],
    idealActivities: ['Problem Solving', 'Building Things', 'Research'],
    idealAnalytical: 'high',
    idealCreativity: 'medium',
    workType: 'both',
    successRate: 90,
    averageRating: 4.8,
    isActive: true,
  },
  {
    name: 'FSc Pre-Medical',
    shortName: 'FSC-MED',
    level: 'intermediate',
    targetAudience: ['matric', 'olevel'],
    institutionType: 'Higher Secondary Colleges',
    field: 'Medical',
    description: '2-year intensive science curriculum covering Biology, Chemistry, and Physics. Standard prerequisite for MBBS, BDS, Pharm-D, DPT, and Biotechnology.',
    duration: '2 years',
    requiredSubjects: ['Biology', 'Chemistry', 'Physics'],
    requiredStream: ['science', 'matric-science', 'pre-medical'],
    minGPA: 3.0,
    universities: [
      { name: 'Kinnaird College for Women', location: 'Lahore', ranking: 1, feePerYear: 'PKR 95,000', hasScholarship: true, admissionTest: 'Matric Merit', website: 'https://kinnaird.edu.pk' },
      { name: 'GCU Lahore', location: 'Lahore', ranking: 2, feePerYear: 'PKR 45,000', hasScholarship: true, admissionTest: 'Matric BISE Merit', website: 'https://gcu.edu.pk' },
      { name: 'Punjab Group of Colleges (PGC)', location: 'Nationwide', ranking: 3, feePerYear: 'PKR 85,000', hasScholarship: true, admissionTest: 'Matric Merit', website: 'https://pgc.edu' },
      { name: 'KIPS College', location: 'Lahore / Islamabad / Multan', ranking: 4, feePerYear: 'PKR 90,000', hasScholarship: true, admissionTest: 'Matric Merit', website: 'https://kips.edu.pk' },
    ],
    careerOutcomes: ['Pathway to MBBS / BDS Doctor', 'Pathway to Doctor of Pharmacy (Pharm-D)', 'Pathway to Doctor of Physical Therapy (DPT)', 'Pathway to BS Biotechnology & Genetics'],
    expectedSalary: 'Medical Entry Foundation (Leads to PKR 85k-450k/mo Healthcare careers)',
    jobMarket: 'excellent',
    idealInterestAreas: ['Healthcare', 'Research', 'Social Work'],
    idealActivities: ['Helping People', 'Research', 'Problem Solving'],
    idealAnalytical: 'high',
    idealCreativity: 'medium',
    workType: 'both',
    successRate: 92,
    averageRating: 4.9,
    isActive: true,
  },
  {
    name: 'ICS (Computer Science & Mathematics)',
    shortName: 'ICS',
    level: 'intermediate',
    targetAudience: ['matric', 'olevel'],
    institutionType: 'Higher Secondary Colleges & Tech Schools',
    field: 'Technology',
    description: '2-year Intermediate in Computer Science focusing on C Programming, Boolean Algebra, Mathematics, and Physics or Statistics. Direct fast-track into BSCS, Software Engineering, and AI.',
    duration: '2 years',
    requiredSubjects: ['Mathematics', 'Computer', 'Physics'],
    requiredStream: ['science', 'matric-science', 'ics', 'technology'],
    minGPA: 2.4,
    universities: [
      { name: 'Punjab Group of Colleges (PGC)', location: 'Lahore / Rawalpindi / Faisalabad', ranking: 1, feePerYear: 'PKR 80,000', hasScholarship: true, admissionTest: 'Matric Merit', website: 'https://pgc.edu' },
      { name: 'GCU Lahore', location: 'Lahore', ranking: 2, feePerYear: 'PKR 45,000', hasScholarship: true, admissionTest: 'Matric BISE Merit', website: 'https://gcu.edu.pk' },
      { name: 'Forman Christian College (FCCU)', location: 'Lahore', ranking: 3, feePerYear: 'PKR 120,000', hasScholarship: true, admissionTest: 'FCCU Test', website: 'https://fccollege.edu.pk' },
      { name: 'Superior College', location: 'Lahore / Multan / Sialkot', ranking: 4, feePerYear: 'PKR 75,000', hasScholarship: true, admissionTest: 'Matric Merit', website: 'https://superior.edu.pk' },
    ],
    careerOutcomes: ['Direct Pathway to BSCS / BSSE / BSAI', 'Junior Web Developer / Freelancer', 'Pathway to BS Data Science & Cyber Security'],
    expectedSalary: 'Tech Foundation (Leads to PKR 90k-400k/mo Software & AI roles)',
    jobMarket: 'excellent',
    idealInterestAreas: ['Technology', 'Engineering'],
    idealActivities: ['Problem Solving', 'Building Things', 'Data Analysis'],
    idealAnalytical: 'high',
    idealCreativity: 'medium',
    workType: 'both',
    successRate: 88,
    averageRating: 4.8,
    isActive: true,
  },
  {
    name: 'I.Com (Intermediate in Commerce)',
    shortName: 'ICOM',
    level: 'intermediate',
    targetAudience: ['matric', 'olevel'],
    institutionType: 'Commerce Colleges & Business Institutes',
    field: 'Business',
    description: '2-year commerce program covering Accounting, Principles of Commerce, Commercial Geography, and Business Math. Stepping stone into BBA, BAF, CA, and ACCA.',
    duration: '2 years',
    requiredSubjects: ['English', 'Mathematics', 'Economics'],
    requiredStream: ['any', 'commerce', 'matric-arts', 'science'],
    minGPA: 2.0,
    universities: [
      { name: 'Punjab College of Commerce', location: 'Lahore / Islamabad / Karachi', ranking: 1, feePerYear: 'PKR 70,000', hasScholarship: true, admissionTest: 'Matric Merit', website: 'https://pgc.edu' },
      { name: 'Hailey College Associate Section', location: 'Lahore', ranking: 2, feePerYear: 'PKR 35,000', hasScholarship: true, admissionTest: 'BISE Merit', website: 'https://pu.edu.pk' },
      { name: 'Concordia College', location: 'Lahore / Gujranwala', ranking: 3, feePerYear: 'PKR 65,000', hasScholarship: true, admissionTest: 'Matric Merit', website: 'https://concordia.edu.pk' },
    ],
    careerOutcomes: ['Pathway to BBA / BS Accounting & Finance', 'Pathway to CA (Chartered Accountancy) / ACCA', 'Junior Bookkeeper / Accounts Assistant'],
    expectedSalary: 'Business Foundation (Leads to PKR 75k-300k/mo Finance careers)',
    jobMarket: 'good',
    idealInterestAreas: ['Business', 'Finance'],
    idealActivities: ['Data Analysis', 'Leadership', 'Communication'],
    idealAnalytical: 'medium',
    idealCreativity: 'low',
    workType: 'both',
    successRate: 86,
    averageRating: 4.5,
    isActive: true,
  },
  {
    name: 'FA (Humanities, Fine Arts & General Science)',
    shortName: 'FA',
    level: 'intermediate',
    targetAudience: ['matric', 'olevel'],
    institutionType: 'Arts & Humanities Colleges',
    field: 'Arts',
    description: '2-year flexible arts and social sciences program covering Psychology, Sociology, Civics, Fine Arts, English Literature, and Mass Communication. Direct entry into LLB, Psychology, and Media.',
    duration: '2 years',
    requiredSubjects: ['English', 'Pakistan Studies', 'Art'],
    requiredStream: ['any', 'arts', 'humanities'],
    minGPA: 2.0,
    universities: [
      { name: 'GCU Lahore Arts Faculty', location: 'Lahore', ranking: 1, feePerYear: 'PKR 40,000', hasScholarship: true, admissionTest: 'Matric Merit', website: 'https://gcu.edu.pk' },
      { name: 'Lahore College for Women University (LCWU)', location: 'Lahore', ranking: 2, feePerYear: 'PKR 35,000', hasScholarship: true, admissionTest: 'Matric Merit', website: 'https://lcwu.edu.pk' },
      { name: 'Kinnaird College', location: 'Lahore', ranking: 3, feePerYear: 'PKR 90,000', hasScholarship: true, admissionTest: 'KC Test', website: 'https://kinnaird.edu.pk' },
    ],
    careerOutcomes: ['Pathway to 5-Year LLB Law Degree', 'Pathway to BS Clinical Psychology', 'Pathway to B.Arch & Graphic Design (NCA/IVS)', 'Pathway to CSS / Civil Services'],
    expectedSalary: 'Arts & Law Foundation (Leads to PKR 70k-350k/mo Professional careers)',
    jobMarket: 'good',
    idealInterestAreas: ['Arts & Media', 'Social Work', 'Law'],
    idealActivities: ['Communication', 'Creativity', 'Research'],
    idealAnalytical: 'medium',
    idealCreativity: 'high',
    workType: 'both',
    successRate: 85,
    averageRating: 4.5,
    isActive: true,
  },
  {
    name: 'DAE (Diploma of Associate Engineering - 3 Years)',
    shortName: 'DAE',
    level: 'diploma',
    targetAudience: ['matric', 'olevel'],
    institutionType: 'Government Colleges of Technology (GCT) & PBTE Institutes',
    field: 'Engineering',
    description: '3-year hands-on technical engineering diploma accredited by Technical Education Boards (PBTE/SBTE). Available in Electrical, Mechanical, Civil, Electronics, and IT. Direct gateway to industry or BS Engineering lateral quota.',
    duration: '3 years',
    requiredSubjects: ['Mathematics', 'Physics', 'Chemistry'],
    requiredStream: ['science', 'matric-science', 'technology', 'dae'],
    minGPA: 2.2,
    universities: [
      { name: 'Government College of Technology (GCT Railway Road)', location: 'Lahore', ranking: 1, feePerYear: 'PKR 25,000', hasScholarship: true, admissionTest: 'Matric Science Merit', website: 'https://tevta.gop.pk' },
      { name: 'Swedish Pakistani Institute of Technology', location: 'Gujrat / Rawalpindi', ranking: 2, feePerYear: 'PKR 30,000', hasScholarship: true, admissionTest: 'TEVTA Merit', website: 'https://tevta.gop.pk' },
      { name: 'GCT Peshawar', location: 'Peshawar', ranking: 3, feePerYear: 'PKR 20,000', hasScholarship: true, admissionTest: 'KP TEVTA Merit', website: 'https://kptevta.gov.pk' },
    ],
    careerOutcomes: ['Associate Electrical / Mechanical Engineer', 'Sub-Engineer (WAPDA / C&W / Railways)', 'Industrial Automation Technician', 'Lateral Entry to BSEE / BSME / BS Civil'],
    expectedSalary: 'PKR 45,000 - 130,000/month',
    jobMarket: 'excellent',
    idealInterestAreas: ['Engineering', 'Technology'],
    idealActivities: ['Building Things', 'Fieldwork', 'Problem Solving'],
    idealAnalytical: 'medium',
    idealCreativity: 'medium',
    workType: 'practical',
    successRate: 91,
    averageRating: 4.6,
    isActive: true,
  },

  // ══════════════════════════════════════════════════════════
  // ── 2. LATERAL BS 5TH SEMESTER (For ADP / BA / BSc 2-Year)
  // ══════════════════════════════════════════════════════════
  {
    name: 'BS Computer Science (Lateral 5th Semester Entry)',
    shortName: 'BSCS-LAT',
    level: 'lateral_bs',
    targetAudience: ['adp', 'ba_bsc'],
    institutionType: 'Universities & HEC Conversion Centers',
    field: 'Technology',
    description: '2-year accelerated conversion program for 2-year ADP / BSc graduates to upgrade their degree into a full 4-year HEC-recognized BS Computer Science degree.',
    duration: '2 years',
    requiredSubjects: ['Mathematics', 'Computer'],
    requiredStream: ['technology', 'science', 'ics'],
    minGPA: 2.5,
    universities: [
      { name: 'Punjab University (PUCIT Lateral Entry)', location: 'Lahore', ranking: 1, feePerYear: 'PKR 55,000', hasScholarship: true, admissionTest: 'PU Entry Test', website: 'https://pucit.edu.pk' },
      { name: 'University of Management & Technology (UMT)', location: 'Lahore', ranking: 2, feePerYear: 'PKR 190,000', hasScholarship: true, admissionTest: 'UMT Test', website: 'https://umt.edu.pk' },
      { name: 'Superior University', location: 'Lahore', ranking: 3, feePerYear: 'PKR 160,000', hasScholarship: true, admissionTest: 'Superior Test', website: 'https://superior.edu.pk' },
    ],
    careerOutcomes: ['Software Engineer', 'Full Stack Developer', 'Cloud Architect', 'DevOps Specialist'],
    expectedSalary: 'PKR 85,000 - 280,000/month',
    jobMarket: 'excellent',
    idealInterestAreas: ['Technology', 'Engineering'],
    idealActivities: ['Problem Solving', 'Building Things', 'Data Analysis'],
    idealAnalytical: 'high',
    idealCreativity: 'medium',
    workType: 'both',
    successRate: 87,
    averageRating: 4.7,
    isActive: true,
  },
  {
    name: 'BBA (Lateral 5th Semester / 2-Year Post-ADP)',
    shortName: 'BBA-LAT',
    level: 'lateral_bs',
    targetAudience: ['adp', 'ba_bsc'],
    institutionType: 'Universities & Business Schools',
    field: 'Business',
    description: '2-year lateral bachelor program designed for ADP in Commerce, Business, or 2-Year B.Com graduates to complete 4-year BBA equivalence.',
    duration: '2 years',
    requiredSubjects: ['Accounting', 'Mathematics', 'English'],
    requiredStream: ['commerce', 'any', 'business'],
    minGPA: 2.4,
    universities: [
      { name: 'Institute of Business Administration (IBA PU)', location: 'Lahore', ranking: 1, feePerYear: 'PKR 65,000', hasScholarship: true, admissionTest: 'PU Test', website: 'https://ibapu.edu.pk' },
      { name: 'University of Central Punjab (UCP)', location: 'Lahore', ranking: 2, feePerYear: 'PKR 185,000', hasScholarship: true, admissionTest: 'UCP Test', website: 'https://ucp.edu.pk' },
      { name: 'Szabist Islamabad', location: 'Islamabad', ranking: 3, feePerYear: 'PKR 210,000', hasScholarship: true, admissionTest: 'Szabist Test', website: 'https://szabist-isb.edu.pk' },
    ],
    careerOutcomes: ['Marketing Executive', 'Financial Analyst', 'HR Specialist', 'Supply Chain Coordinator'],
    expectedSalary: 'PKR 75,000 - 250,000/month',
    jobMarket: 'good',
    idealInterestAreas: ['Business', 'Finance'],
    idealActivities: ['Leadership', 'Communication', 'Problem Solving'],
    idealAnalytical: 'medium',
    idealCreativity: 'medium',
    workType: 'both',
    successRate: 86,
    averageRating: 4.6,
    isActive: true,
  },

  // ══════════════════════════════════════════════════════════
  // ── 3. POSTGRADUATE & MASTER'S (For 4-Year BS Graduates)
  // ══════════════════════════════════════════════════════════
  {
    name: 'MS Computer Science & Artificial Intelligence',
    shortName: 'MSCS',
    level: 'master',
    targetAudience: ['bachelor', 'master'],
    institutionType: 'Universities & Research Institutes',
    field: 'Technology',
    description: '2-year advanced postgraduate research degree covering Deep Learning, Distributed Cloud Computing, High-Performance Computing, and Thesis Research.',
    duration: '2 years',
    requiredSubjects: ['Computer', 'Mathematics', 'Algorithms'],
    requiredStream: ['technology', 'science', 'engineering'],
    minGPA: 2.5,
    universities: [
      { name: 'FAST-NUCES Graduate School', location: 'Islamabad / Lahore / Karachi', ranking: 1, feePerYear: 'PKR 180,000', hasScholarship: true, admissionTest: 'NTS GAT-General / FAST Test', website: 'https://nu.edu.pk' },
      { name: 'NUST (SEECS)', location: 'Islamabad', ranking: 2, feePerYear: 'PKR 190,000', hasScholarship: true, admissionTest: 'GAT / NUST GNET', website: 'https://nust.edu.pk' },
      { name: 'LUMS (SBASSE)', location: 'Lahore', ranking: 3, feePerYear: 'PKR 650,000', hasScholarship: true, admissionTest: 'LGAT / GRE', website: 'https://lums.edu.pk' },
      { name: 'Information Technology University (ITU)', location: 'Lahore', ranking: 4, feePerYear: 'PKR 195,000', hasScholarship: true, admissionTest: 'ITU Grad Test', website: 'https://itu.edu.pk' },
    ],
    careerOutcomes: ['Principal AI Scientist', 'Senior Solutions Architect', 'University Lecturer / Researcher', 'PhD Candidate at Top Global Labs'],
    expectedSalary: 'PKR 160,000 - 600,000/month',
    jobMarket: 'excellent',
    idealInterestAreas: ['Technology', 'Research'],
    idealActivities: ['Research', 'Problem Solving', 'Data Analysis'],
    idealAnalytical: 'high',
    idealCreativity: 'high',
    workType: 'both',
    successRate: 91,
    averageRating: 4.9,
    isActive: true,
  },
  {
    name: 'MBA (Master of Business Administration - 2 Years)',
    shortName: 'MBA',
    level: 'master',
    targetAudience: ['bachelor', 'master'],
    institutionType: 'Top Business Schools',
    field: 'Business',
    description: '2-year executive leadership degree focusing on Corporate Strategy, Strategic Marketing, Venture Capital, Global Supply Chain, and Executive Management.',
    duration: '2 years',
    requiredSubjects: ['English', 'Mathematics'],
    requiredStream: ['any', 'business', 'commerce', 'technology', 'engineering'],
    minGPA: 2.5,
    universities: [
      { name: 'LUMS (Suleman Dawood School of Business)', location: 'Lahore', ranking: 1, feePerYear: 'PKR 950,000', hasScholarship: true, admissionTest: 'GMAT / NMAT / LMAT', website: 'https://lums.edu.pk' },
      { name: 'IBA Karachi', location: 'Karachi', ranking: 2, feePerYear: 'PKR 620,000', hasScholarship: true, admissionTest: 'IBA Graduate Test', website: 'https://iba.edu.pk' },
      { name: 'NUST (NBS)', location: 'Islamabad', ranking: 3, feePerYear: 'PKR 260,000', hasScholarship: true, admissionTest: 'GAT-General', website: 'https://nust.edu.pk' },
      { name: 'Lahore School of Economics (LSE)', location: 'Lahore', ranking: 4, feePerYear: 'PKR 520,000', hasScholarship: true, admissionTest: 'LSE Grad Test', website: 'https://lahoreschoolofeconomics.edu.pk' },
    ],
    careerOutcomes: ['Senior Management Consultant', 'Vice President / Director of Operations', 'Chief Marketing Officer (CMO)', 'Investment Portfolio Director'],
    expectedSalary: 'PKR 180,000 - 700,000/month',
    jobMarket: 'excellent',
    idealInterestAreas: ['Business', 'Finance', 'Education'],
    idealActivities: ['Leadership', 'Communication', 'Problem Solving'],
    idealAnalytical: 'high',
    idealCreativity: 'high',
    workType: 'both',
    successRate: 93,
    averageRating: 4.9,
    isActive: true,
  },

  // ══════════════════════════════════════════════════════════
  // ── 4. BACHELOR'S DEGREES (4 - 5 Years For HSSC / A-Levels)
  // ══════════════════════════════════════════════════════════
  {
    name: 'BS Computer Science',
    shortName: 'BSCS',
    level: 'bachelor',
    targetAudience: ['intermediate', 'ics', 'fsc', 'dae', 'alevel'],
    institutionType: 'Universities & DAIs',
    field: 'Technology',
    description: 'Core foundation in algorithms, software development, cloud computing, distributed systems, and AI.',
    duration: '4 years',
    requiredSubjects: ['Mathematics', 'Computer', 'Physics'],
    requiredStream: ['science', 'technology', 'ics', 'pre-engineering'],
    minGPA: 2.5,
    universities: [
      { name: 'FAST-NUCES', location: 'Lahore / Karachi / Islamabad', ranking: 1, feePerYear: 'PKR 220,000', hasScholarship: true, admissionTest: 'NU Entry Test', website: 'https://nu.edu.pk' },
      { name: 'NUST (SEECS)', location: 'Islamabad', ranking: 2, feePerYear: 'PKR 240,000', hasScholarship: true, admissionTest: 'NET (NUST Entry Test)', website: 'https://nust.edu.pk' },
      { name: 'LUMS (SBASSE)', location: 'Lahore', ranking: 3, feePerYear: 'PKR 850,000', hasScholarship: true, admissionTest: 'SAT / LCAT', website: 'https://lums.edu.pk' },
      { name: 'COMSATS University', location: 'Islamabad / Lahore / Wah', ranking: 4, feePerYear: 'PKR 140,000', hasScholarship: true, admissionTest: 'NTS NAT-ICS/IE', website: 'https://comsats.edu.pk' },
      { name: 'Punjab University (PUCIT)', location: 'Lahore', ranking: 5, feePerYear: 'PKR 55,000', hasScholarship: true, admissionTest: 'PU Entry Test', website: 'https://pucit.edu.pk' },
      { name: 'Information Technology University (ITU)', location: 'Lahore', ranking: 6, feePerYear: 'PKR 210,000', hasScholarship: true, admissionTest: 'ITU Admissions Test', website: 'https://itu.edu.pk' },
    ],
    careerOutcomes: ['Software Engineer', 'Full Stack Developer', 'Cloud Architect', 'Systems Analyst', 'DevOps Engineer', 'AI Developer'],
    expectedSalary: 'PKR 90,000 - 350,000/month',
    jobMarket: 'excellent',
    idealInterestAreas: ['Technology', 'Engineering'],
    idealActivities: ['Problem Solving', 'Building Things', 'Research'],
    idealAnalytical: 'high',
    idealCreativity: 'medium',
    workType: 'both',
    successRate: 88,
    averageRating: 4.8,
    isActive: true,
  },
  {
    name: 'BS Software Engineering',
    shortName: 'BSSE',
    level: 'bachelor',
    targetAudience: ['intermediate', 'ics', 'fsc', 'dae', 'alevel'],
    institutionType: 'Universities & DAIs',
    field: 'Technology',
    description: 'Systematic approach to software architecture, large-scale design patterns, testing, agile management, and CI/CD.',
    duration: '4 years',
    requiredSubjects: ['Mathematics', 'Computer', 'Physics'],
    requiredStream: ['science', 'technology', 'ics', 'pre-engineering'],
    minGPA: 2.5,
    universities: [
      { name: 'NUST (SEECS)', location: 'Islamabad', ranking: 1, feePerYear: 'PKR 240,000', hasScholarship: true, admissionTest: 'NET', website: 'https://nust.edu.pk' },
      { name: 'FAST-NUCES', location: 'Lahore / Karachi / Islamabad', ranking: 2, feePerYear: 'PKR 220,000', hasScholarship: true, admissionTest: 'NU Test', website: 'https://nu.edu.pk' },
      { name: 'GIKI', location: 'Topi, Swabi', ranking: 3, feePerYear: 'PKR 580,000', hasScholarship: true, admissionTest: 'GIKI Test', website: 'https://giki.edu.pk' },
      { name: 'Bahria University', location: 'Islamabad / Karachi', ranking: 4, feePerYear: 'PKR 160,000', hasScholarship: true, admissionTest: 'Bahria CBT', website: 'https://bahria.edu.pk' },
      { name: 'Air University', location: 'Islamabad', ranking: 5, feePerYear: 'PKR 150,000', hasScholarship: true, admissionTest: 'AU Entry Test', website: 'https://au.edu.pk' },
    ],
    careerOutcomes: ['Software Engineer', 'QA Automation Lead', 'DevOps Architect', 'Scrum Master', 'Technical Product Manager'],
    expectedSalary: 'PKR 90,000 - 320,000/month',
    jobMarket: 'excellent',
    idealInterestAreas: ['Technology', 'Engineering'],
    idealActivities: ['Building Things', 'Problem Solving', 'Leadership'],
    idealAnalytical: 'high',
    idealCreativity: 'medium',
    workType: 'practical',
    successRate: 86,
    averageRating: 4.7,
    isActive: true,
  },
  {
    name: 'BS Artificial Intelligence',
    shortName: 'BSAI',
    level: 'bachelor',
    targetAudience: ['intermediate', 'ics', 'fsc', 'dae', 'alevel'],
    institutionType: 'Universities & DAIs',
    field: 'Technology',
    description: 'Deep neural networks, computer vision, natural language processing, reinforcement learning, and autonomous systems.',
    duration: '4 years',
    requiredSubjects: ['Mathematics', 'Computer', 'Statistics'],
    requiredStream: ['science', 'technology', 'ics', 'pre-engineering'],
    minGPA: 2.8,
    universities: [
      { name: 'FAST-NUCES', location: 'Islamabad / Lahore / Karachi', ranking: 1, feePerYear: 'PKR 220,000', hasScholarship: true, admissionTest: 'NU Entry Test', website: 'https://nu.edu.pk' },
      { name: 'NUST (SEECS)', location: 'Islamabad', ranking: 2, feePerYear: 'PKR 240,000', hasScholarship: true, admissionTest: 'NET', website: 'https://nust.edu.pk' },
      { name: 'Air University', location: 'Islamabad', ranking: 3, feePerYear: 'PKR 160,000', hasScholarship: true, admissionTest: 'AU Entry Test', website: 'https://au.edu.pk' },
      { name: 'Information Technology University (ITU)', location: 'Lahore', ranking: 4, feePerYear: 'PKR 220,000', hasScholarship: true, admissionTest: 'ITU Test', website: 'https://itu.edu.pk' },
      { name: 'COMSATS', location: 'Islamabad / Lahore', ranking: 5, feePerYear: 'PKR 145,000', hasScholarship: true, admissionTest: 'NTS NAT', website: 'https://comsats.edu.pk' },
    ],
    careerOutcomes: ['AI Engineer', 'Machine Learning Specialist', 'Computer Vision Engineer', 'NLP Researcher', 'Generative AI Developer'],
    expectedSalary: 'PKR 110,000 - 450,000/month',
    jobMarket: 'excellent',
    idealInterestAreas: ['Technology', 'Research'],
    idealActivities: ['Problem Solving', 'Research', 'Data Analysis'],
    idealAnalytical: 'high',
    idealCreativity: 'high',
    workType: 'both',
    successRate: 89,
    averageRating: 4.9,
    isActive: true,
  },
  {
    name: 'BS Data Science',
    shortName: 'BSDS',
    level: 'bachelor',
    targetAudience: ['intermediate', 'ics', 'fsc', 'dae', 'alevel'],
    institutionType: 'Universities & DAIs',
    field: 'Technology',
    description: 'Big data pipelines, statistical modeling, predictive analytics, business intelligence, and predictive modeling.',
    duration: '4 years',
    requiredSubjects: ['Mathematics', 'Statistics', 'Computer'],
    requiredStream: ['science', 'technology', 'ics', 'commerce', 'pre-engineering'],
    minGPA: 2.5,
    universities: [
      { name: 'FAST-NUCES', location: 'Lahore / Islamabad', ranking: 1, feePerYear: 'PKR 220,000', hasScholarship: true, admissionTest: 'NU Test', website: 'https://nu.edu.pk' },
      { name: 'ITU Lahore', location: 'Lahore', ranking: 2, feePerYear: 'PKR 210,000', hasScholarship: true, admissionTest: 'ITU Test', website: 'https://itu.edu.pk' },
      { name: 'NUST', location: 'Islamabad', ranking: 3, feePerYear: 'PKR 240,000', hasScholarship: true, admissionTest: 'NET', website: 'https://nust.edu.pk' },
      { name: 'COMSATS', location: 'Islamabad / Lahore', ranking: 4, feePerYear: 'PKR 140,000', hasScholarship: true, admissionTest: 'NTS NAT', website: 'https://comsats.edu.pk' },
    ],
    careerOutcomes: ['Data Scientist', 'BI Analyst', 'Data Engineer', 'Quantitative Analyst', 'Machine Learning Engineer'],
    expectedSalary: 'PKR 95,000 - 350,000/month',
    jobMarket: 'excellent',
    idealInterestAreas: ['Technology', 'Finance', 'Research'],
    idealActivities: ['Data Analysis', 'Problem Solving', 'Research'],
    idealAnalytical: 'high',
    idealCreativity: 'medium',
    workType: 'both',
    successRate: 87,
    averageRating: 4.7,
    isActive: true,
  },
  {
    name: 'BS Cyber Security',
    shortName: 'BSCY',
    level: 'bachelor',
    targetAudience: ['intermediate', 'ics', 'fsc', 'dae', 'alevel'],
    institutionType: 'Universities & DAIs',
    field: 'Technology',
    description: 'Information security, network defense, ethical hacking, digital forensics, threat intelligence, and cryptography.',
    duration: '4 years',
    requiredSubjects: ['Mathematics', 'Computer', 'Physics'],
    requiredStream: ['science', 'technology', 'ics', 'pre-engineering'],
    minGPA: 2.5,
    universities: [
      { name: 'Air University (NCCS)', location: 'Islamabad', ranking: 1, feePerYear: 'PKR 160,000', hasScholarship: true, admissionTest: 'AU Test', website: 'https://au.edu.pk' },
      { name: 'FAST-NUCES', location: 'Islamabad / Lahore', ranking: 2, feePerYear: 'PKR 220,000', hasScholarship: true, admissionTest: 'NU Test', website: 'https://nu.edu.pk' },
      { name: 'NUST', location: 'Islamabad', ranking: 3, feePerYear: 'PKR 240,000', hasScholarship: true, admissionTest: 'NET', website: 'https://nust.edu.pk' },
      { name: 'Bahria University', location: 'Islamabad / Karachi', ranking: 4, feePerYear: 'PKR 160,000', hasScholarship: true, admissionTest: 'Bahria CBT', website: 'https://bahria.edu.pk' },
    ],
    careerOutcomes: ['Cyber Security Analyst', 'Penetration Tester', 'SOC Analyst', 'Security Architect', 'Information Security Officer'],
    expectedSalary: 'PKR 100,000 - 380,000/month',
    jobMarket: 'excellent',
    idealInterestAreas: ['Technology', 'Law'],
    idealActivities: ['Problem Solving', 'Building Things', 'Research'],
    idealAnalytical: 'high',
    idealCreativity: 'medium',
    workType: 'practical',
    successRate: 85,
    averageRating: 4.8,
    isActive: true,
  },
  {
    name: 'MBBS (Bachelor of Medicine & Surgery)',
    shortName: 'MBBS',
    level: 'bachelor',
    targetAudience: ['intermediate', 'fsc', 'alevel'],
    institutionType: 'Medical Universities & Teaching Hospitals',
    field: 'Medical',
    description: 'Comprehensive 5-year medical education covering human anatomy, pathology, pharmacology, internal medicine, surgery, and clinical diagnosis.',
    duration: '5 years',
    requiredSubjects: ['Biology', 'Chemistry', 'Physics'],
    requiredStream: ['science', 'pre-medical'],
    minGPA: 3.5,
    universities: [
      { name: 'King Edward Medical University (KEMU)', location: 'Lahore', ranking: 1, feePerYear: 'PKR 45,000', hasScholarship: true, admissionTest: 'PMDC MDCAT', website: 'https://kemu.edu.pk' },
      { name: 'Aga Khan University (AKU)', location: 'Karachi', ranking: 2, feePerYear: 'PKR 1,450,000', hasScholarship: true, admissionTest: 'AKU Test + MDCAT', website: 'https://aku.edu' },
      { name: 'Allama Iqbal Medical College (AIMC)', location: 'Lahore', ranking: 3, feePerYear: 'PKR 45,000', hasScholarship: true, admissionTest: 'MDCAT', website: 'https://aimc.edu.pk' },
      { name: 'Dow University of Health Sciences (DUHS)', location: 'Karachi', ranking: 4, feePerYear: 'PKR 65,000', hasScholarship: true, admissionTest: 'MDCAT', website: 'https://duhs.edu.pk' },
      { name: 'Rawalpindi Medical University (RMU)', location: 'Rawalpindi', ranking: 5, feePerYear: 'PKR 45,000', hasScholarship: true, admissionTest: 'MDCAT', website: 'https://rmur.edu.pk' },
      { name: 'Shifa College of Medicine', location: 'Islamabad', ranking: 6, feePerYear: 'PKR 1,300,000', hasScholarship: true, admissionTest: 'MDCAT', website: 'https://shifa.edu.pk' },
    ],
    careerOutcomes: ['Medical Officer', 'Consultant Physician', 'General Surgeon', 'Pediatrician', 'Cardiologist', 'Medical Researcher'],
    expectedSalary: 'PKR 85,000 - 450,000/month',
    jobMarket: 'excellent',
    idealInterestAreas: ['Healthcare', 'Research', 'Social Work'],
    idealActivities: ['Helping People', 'Research', 'Problem Solving'],
    idealAnalytical: 'high',
    idealCreativity: 'medium',
    workType: 'practical',
    successRate: 92,
    averageRating: 4.9,
    isActive: true,
  },
  {
    name: 'BDS (Bachelor of Dental Surgery)',
    shortName: 'BDS',
    level: 'bachelor',
    targetAudience: ['intermediate', 'fsc', 'alevel'],
    institutionType: 'Dental Colleges & Hospitals',
    field: 'Medical',
    description: 'Oral surgery, orthodontics, periodontology, dental prosthetics, restorative dentistry, and dental radiology.',
    duration: '4 years',
    requiredSubjects: ['Biology', 'Chemistry', 'Physics'],
    requiredStream: ['science', 'pre-medical'],
    minGPA: 3.2,
    universities: [
      { name: "de'Montmorency College of Dentistry", location: 'Lahore', ranking: 1, feePerYear: 'PKR 45,000', hasScholarship: true, admissionTest: 'MDCAT', website: 'https://dcd.edu.pk' },
      { name: 'Aga Khan University Dental Hospital', location: 'Karachi', ranking: 2, feePerYear: 'PKR 1,350,000', hasScholarship: true, admissionTest: 'AKU Test + MDCAT', website: 'https://aku.edu' },
      { name: 'Fatima Jinnah Medical University Dental Section', location: 'Lahore', ranking: 3, feePerYear: 'PKR 45,000', hasScholarship: true, admissionTest: 'MDCAT', website: 'https://fjmu.edu.pk' },
      { name: 'Liaquat University of Medical Sciences (LUMHS)', location: 'Jamshoro', ranking: 4, feePerYear: 'PKR 55,000', hasScholarship: true, admissionTest: 'MDCAT', website: 'https://lumhs.edu.pk' },
    ],
    careerOutcomes: ['Dental Surgeon', 'Orthodontist', 'Prosthodontist', 'Cosmetic Dentist', 'Oral & Maxillofacial Surgeon'],
    expectedSalary: 'PKR 80,000 - 350,000/month',
    jobMarket: 'good',
    idealInterestAreas: ['Healthcare', 'Arts & Media'],
    idealActivities: ['Helping People', 'Building Things', 'Problem Solving'],
    idealAnalytical: 'high',
    idealCreativity: 'high',
    workType: 'practical',
    successRate: 88,
    averageRating: 4.6,
    isActive: true,
  },
  {
    name: 'Doctor of Pharmacy (Pharm-D)',
    shortName: 'PharmD',
    level: 'bachelor',
    targetAudience: ['intermediate', 'fsc', 'alevel'],
    institutionType: 'Pharmacy Colleges & Universities',
    field: 'Medical',
    description: 'Clinical pharmacy, pharmaceutical chemistry, drug discovery, toxicology, industrial formulation, and patient pharmacology.',
    duration: '5 years',
    requiredSubjects: ['Biology', 'Chemistry', 'Physics'],
    requiredStream: ['science', 'pre-medical'],
    minGPA: 2.8,
    universities: [
      { name: 'Punjab University College of Pharmacy', location: 'Lahore', ranking: 1, feePerYear: 'PKR 50,000', hasScholarship: true, admissionTest: 'PU Entry Test', website: 'https://pu.edu.pk' },
      { name: 'Dow College of Pharmacy', location: 'Karachi', ranking: 2, feePerYear: 'PKR 90,000', hasScholarship: true, admissionTest: 'Dow Test', website: 'https://duhs.edu.pk' },
      { name: 'Quaid-e-Azam University (QAU)', location: 'Islamabad', ranking: 3, feePerYear: 'PKR 65,000', hasScholarship: true, admissionTest: 'QAU Test', website: 'https://qau.edu.pk' },
      { name: 'Riphah Institute of Pharmaceutical Sciences', location: 'Islamabad / Lahore', ranking: 4, feePerYear: 'PKR 210,000', hasScholarship: true, admissionTest: 'Riphah Test', website: 'https://riphah.edu.pk' },
    ],
    careerOutcomes: ['Clinical Pharmacist', 'Pharmaceutical QC Specialist', 'Regulatory Affairs Manager', 'Hospital Pharmacist', 'Drug Research Scientist'],
    expectedSalary: 'PKR 65,000 - 250,000/month',
    jobMarket: 'good',
    idealInterestAreas: ['Healthcare', 'Research'],
    idealActivities: ['Research', 'Helping People', 'Data Analysis'],
    idealAnalytical: 'high',
    idealCreativity: 'medium',
    workType: 'both',
    successRate: 84,
    averageRating: 4.5,
    isActive: true,
  },
  {
    name: 'Doctor of Physical Therapy (DPT)',
    shortName: 'DPT',
    level: 'bachelor',
    targetAudience: ['intermediate', 'fsc', 'alevel'],
    institutionType: 'Allied Health Science Institutes',
    field: 'Medical',
    description: 'Neurological, musculoskeletal, pediatric, and cardiopulmonary physical rehabilitation, kinesiology, and sports therapy.',
    duration: '5 years',
    requiredSubjects: ['Biology', 'Chemistry', 'Physics'],
    requiredStream: ['science', 'pre-medical'],
    minGPA: 2.7,
    universities: [
      { name: 'King Edward Medical University (KEMU)', location: 'Lahore', ranking: 1, feePerYear: 'PKR 45,000', hasScholarship: true, admissionTest: 'KEMU Test / MDCAT', website: 'https://kemu.edu.pk' },
      { name: 'Riphah College of Rehabilitation Sciences', location: 'Islamabad / Lahore', ranking: 2, feePerYear: 'PKR 195,000', hasScholarship: true, admissionTest: 'Riphah Test', website: 'https://riphah.edu.pk' },
      { name: 'Shifa Tameer-e-Millat University', location: 'Islamabad', ranking: 3, feePerYear: 'PKR 220,000', hasScholarship: true, admissionTest: 'STMU Test', website: 'https://stmu.edu.pk' },
      { name: 'University of Health Sciences (UHS)', location: 'Lahore', ranking: 4, feePerYear: 'PKR 60,000', hasScholarship: true, admissionTest: 'UHS Test', website: 'https://uhs.edu.pk' },
    ],
    careerOutcomes: ['Physical Therapist', 'Sports Rehabilitation Consultant', 'Neuro Physical Therapist', 'Orthopedic Specialist'],
    expectedSalary: 'PKR 60,000 - 220,000/month',
    jobMarket: 'good',
    idealInterestAreas: ['Healthcare', 'Social Work'],
    idealActivities: ['Helping People', 'Fieldwork', 'Problem Solving'],
    idealAnalytical: 'medium',
    idealCreativity: 'medium',
    workType: 'practical',
    successRate: 82,
    averageRating: 4.4,
    isActive: true,
  },
  {
    name: 'BS Nursing (Generic)',
    shortName: 'BSN',
    level: 'bachelor',
    targetAudience: ['intermediate', 'fsc', 'alevel'],
    institutionType: 'Nursing Colleges & Teaching Hospitals',
    field: 'Medical',
    description: 'Patient care, critical care nursing, community health, nursing informatics, surgical assistance, and medical emergency management.',
    duration: '4 years',
    requiredSubjects: ['Biology', 'Chemistry', 'Physics'],
    requiredStream: ['science', 'pre-medical'],
    minGPA: 2.5,
    universities: [
      { name: 'Aga Khan School of Nursing & Midwifery', location: 'Karachi', ranking: 1, feePerYear: 'PKR 350,000', hasScholarship: true, admissionTest: 'AKU Nursing Test', website: 'https://aku.edu' },
      { name: 'Shifa College of Nursing', location: 'Islamabad', ranking: 2, feePerYear: 'PKR 180,000', hasScholarship: true, admissionTest: 'STMU Test', website: 'https://stmu.edu.pk' },
      { name: 'UHS Allied College of Nursing', location: 'Lahore', ranking: 3, feePerYear: 'PKR 35,000', hasScholarship: true, admissionTest: 'PNC Test', website: 'https://uhs.edu.pk' },
      { name: 'Dow Institute of Nursing', location: 'Karachi', ranking: 4, feePerYear: 'PKR 50,000', hasScholarship: true, admissionTest: 'DUHS Test', website: 'https://duhs.edu.pk' },
    ],
    careerOutcomes: ['Staff Nurse', 'ICU Nurse Specialist', 'Nurse Manager', 'Clinical Instructor', 'International Travel Nurse (UK/US/Gulf)'],
    expectedSalary: 'PKR 60,000 - 300,000/month',
    jobMarket: 'excellent',
    idealInterestAreas: ['Healthcare', 'Social Work'],
    idealActivities: ['Helping People', 'Communication', 'Fieldwork'],
    idealAnalytical: 'medium',
    idealCreativity: 'low',
    workType: 'practical',
    successRate: 94,
    averageRating: 4.7,
    isActive: true,
  },
  {
    name: 'BS Electrical Engineering',
    shortName: 'BSEE',
    level: 'bachelor',
    targetAudience: ['intermediate', 'fsc', 'dae', 'alevel'],
    institutionType: 'Engineering Universities (PEC Accredited)',
    field: 'Engineering',
    description: 'Power transmission, renewable energy, electronics, embedded microcontrollers, signal processing, and telecommunications.',
    duration: '4 years',
    requiredSubjects: ['Mathematics', 'Physics', 'Chemistry'],
    requiredStream: ['science', 'pre-engineering', 'dae'],
    minGPA: 2.7,
    universities: [
      { name: 'NUST (SEECS / CEME)', location: 'Islamabad / Rawalpindi', ranking: 1, feePerYear: 'PKR 240,000', hasScholarship: true, admissionTest: 'NET', website: 'https://nust.edu.pk' },
      { name: 'UET Lahore', location: 'Lahore', ranking: 2, feePerYear: 'PKR 85,000', hasScholarship: true, admissionTest: 'ECAT', website: 'https://uet.edu.pk' },
      { name: 'GIKI', location: 'Topi, Swabi', ranking: 3, feePerYear: 'PKR 580,000', hasScholarship: true, admissionTest: 'GIKI Test', website: 'https://giki.edu.pk' },
      { name: 'PIEAS', location: 'Islamabad', ranking: 4, feePerYear: 'PKR 90,000', hasScholarship: true, admissionTest: 'PIEAS Test', website: 'https://pieas.edu.pk' },
      { name: 'FAST-NUCES', location: 'Lahore / Islamabad', ranking: 5, feePerYear: 'PKR 220,000', hasScholarship: true, admissionTest: 'NU Test', website: 'https://nu.edu.pk' },
    ],
    careerOutcomes: ['Power Systems Engineer', 'Embedded Systems Developer', 'Renewable Energy Specialist', 'Telecom Engineer', 'Electronics Design Lead'],
    expectedSalary: 'PKR 80,000 - 280,000/month',
    jobMarket: 'good',
    idealInterestAreas: ['Engineering', 'Technology'],
    idealActivities: ['Building Things', 'Problem Solving', 'Fieldwork'],
    idealAnalytical: 'high',
    idealCreativity: 'medium',
    workType: 'both',
    successRate: 85,
    averageRating: 4.6,
    isActive: true,
  },
  {
    name: 'BS Mechanical Engineering',
    shortName: 'BSME',
    level: 'bachelor',
    targetAudience: ['intermediate', 'fsc', 'dae', 'alevel'],
    institutionType: 'Engineering Universities (PEC Accredited)',
    field: 'Engineering',
    description: 'Thermodynamics, mechanical design, CAD/CAM simulation, aerodynamics, automotive engineering, robotics, and manufacturing.',
    duration: '4 years',
    requiredSubjects: ['Mathematics', 'Physics', 'Chemistry'],
    requiredStream: ['science', 'pre-engineering', 'dae'],
    minGPA: 2.7,
    universities: [
      { name: 'GIKI', location: 'Topi, Swabi', ranking: 1, feePerYear: 'PKR 580,000', hasScholarship: true, admissionTest: 'GIKI Test', website: 'https://giki.edu.pk' },
      { name: 'NUST (SMME)', location: 'Islamabad', ranking: 2, feePerYear: 'PKR 240,000', hasScholarship: true, admissionTest: 'NET', website: 'https://nust.edu.pk' },
      { name: 'UET Lahore', location: 'Lahore', ranking: 3, feePerYear: 'PKR 85,000', hasScholarship: true, admissionTest: 'ECAT', website: 'https://uet.edu.pk' },
      { name: 'NED University', location: 'Karachi', ranking: 4, feePerYear: 'PKR 75,000', hasScholarship: true, admissionTest: 'NED Test', website: 'https://neduet.edu.pk' },
      { name: 'PIEAS', location: 'Islamabad', ranking: 5, feePerYear: 'PKR 90,000', hasScholarship: true, admissionTest: 'PIEAS Test', website: 'https://pieas.edu.pk' },
    ],
    careerOutcomes: ['Mechanical Design Engineer', 'Automotive Engineer', 'HVAC Consultant', 'Production & Manufacturing Manager', 'Maintenance Lead'],
    expectedSalary: 'PKR 80,000 - 300,000/month',
    jobMarket: 'good',
    idealInterestAreas: ['Engineering', 'Architecture'],
    idealActivities: ['Building Things', 'Problem Solving', 'Fieldwork'],
    idealAnalytical: 'high',
    idealCreativity: 'medium',
    workType: 'practical',
    successRate: 83,
    averageRating: 4.6,
    isActive: true,
  },
  {
    name: 'BS Civil Engineering',
    shortName: 'BSCE',
    level: 'bachelor',
    targetAudience: ['intermediate', 'fsc', 'dae', 'alevel'],
    institutionType: 'Engineering Universities (PEC Accredited)',
    field: 'Engineering',
    description: 'Structural engineering, infrastructure planning, geotechnical mechanics, highway design, and construction management.',
    duration: '4 years',
    requiredSubjects: ['Mathematics', 'Physics', 'Chemistry'],
    requiredStream: ['science', 'pre-engineering', 'dae'],
    minGPA: 2.5,
    universities: [
      { name: 'UET Lahore', location: 'Lahore', ranking: 1, feePerYear: 'PKR 85,000', hasScholarship: true, admissionTest: 'ECAT', website: 'https://uet.edu.pk' },
      { name: 'NUST (NICE)', location: 'Islamabad', ranking: 2, feePerYear: 'PKR 240,000', hasScholarship: true, admissionTest: 'NET', website: 'https://nust.edu.pk' },
      { name: 'NED University', location: 'Karachi', ranking: 3, feePerYear: 'PKR 75,000', hasScholarship: true, admissionTest: 'NED Test', website: 'https://neduet.edu.pk' },
      { name: 'UET Taxila', location: 'Taxila', ranking: 4, feePerYear: 'PKR 80,000', hasScholarship: true, admissionTest: 'ECAT', website: 'https://uettaxila.edu.pk' },
    ],
    careerOutcomes: ['Civil Site Engineer', 'Structural Consultant', 'Project Manager (Construction)', 'Transportation Planner', 'Geotechnical Analyst'],
    expectedSalary: 'PKR 75,000 - 280,000/month',
    jobMarket: 'good',
    idealInterestAreas: ['Engineering', 'Architecture', 'Environment'],
    idealActivities: ['Fieldwork', 'Building Things', 'Leadership'],
    idealAnalytical: 'high',
    idealCreativity: 'low',
    workType: 'practical',
    successRate: 84,
    averageRating: 4.5,
    isActive: true,
  },
  {
    name: 'BS Mechatronics & Robotics Engineering',
    shortName: 'BSMTR',
    level: 'bachelor',
    targetAudience: ['intermediate', 'fsc', 'dae', 'alevel'],
    institutionType: 'Engineering Universities (PEC Accredited)',
    field: 'Engineering',
    description: 'Synergy of mechanical engineering, electronics, computer vision, AI, and programmable logic automation controllers.',
    duration: '4 years',
    requiredSubjects: ['Mathematics', 'Physics', 'Computer'],
    requiredStream: ['science', 'pre-engineering', 'technology', 'dae'],
    minGPA: 2.7,
    universities: [
      { name: 'NUST (CEME)', location: 'Rawalpindi', ranking: 1, feePerYear: 'PKR 240,000', hasScholarship: true, admissionTest: 'NET', website: 'https://nust.edu.pk' },
      { name: 'UET Lahore', location: 'Lahore', ranking: 2, feePerYear: 'PKR 85,000', hasScholarship: true, admissionTest: 'ECAT', website: 'https://uet.edu.pk' },
      { name: 'Air University', location: 'Islamabad', ranking: 3, feePerYear: 'PKR 160,000', hasScholarship: true, admissionTest: 'AU Test', website: 'https://au.edu.pk' },
      { name: 'GIKI', location: 'Topi, Swabi', ranking: 4, feePerYear: 'PKR 580,000', hasScholarship: true, admissionTest: 'GIKI Test', website: 'https://giki.edu.pk' },
    ],
    careerOutcomes: ['Robotics Engineer', 'Automation Systems Lead', 'IoT Hardware Engineer', 'Control Systems Specialist', 'Mechatronic Product Designer'],
    expectedSalary: 'PKR 90,000 - 320,000/month',
    jobMarket: 'excellent',
    idealInterestAreas: ['Engineering', 'Technology'],
    idealActivities: ['Building Things', 'Problem Solving', 'Research'],
    idealAnalytical: 'high',
    idealCreativity: 'high',
    workType: 'practical',
    successRate: 86,
    averageRating: 4.8,
    isActive: true,
  },
  {
    name: 'BBA (Bachelor of Business Administration)',
    shortName: 'BBA',
    level: 'bachelor',
    targetAudience: ['intermediate', 'icom', 'ics', 'fsc', 'fa', 'alevel'],
    institutionType: 'Business Schools & DAIs',
    field: 'Business',
    description: 'Corporate strategy, brand marketing, financial management, operations, human resources, and entrepreneurship.',
    duration: '4 years',
    requiredSubjects: ['English', 'Mathematics'],
    requiredStream: ['any', 'commerce', 'science', 'arts'],
    minGPA: 2.5,
    universities: [
      { name: 'IBA Karachi', location: 'Karachi', ranking: 1, feePerYear: 'PKR 550,000', hasScholarship: true, admissionTest: 'IBA Aptitude Test / SAT', website: 'https://iba.edu.pk' },
      { name: 'LUMS (SDSB)', location: 'Lahore', ranking: 2, feePerYear: 'PKR 850,000', hasScholarship: true, admissionTest: 'LCAT / SAT', website: 'https://lums.edu.pk' },
      { name: 'NUST (NBS)', location: 'Islamabad', ranking: 3, feePerYear: 'PKR 240,000', hasScholarship: true, admissionTest: 'NET (Business)', website: 'https://nust.edu.pk' },
      { name: 'Lahore School of Economics (LSE)', location: 'Lahore', ranking: 4, feePerYear: 'PKR 480,000', hasScholarship: true, admissionTest: 'LSE Entry Test', website: 'https://lahoreschoolofeconomics.edu.pk' },
      { name: 'FAST School of Management', location: 'Lahore / Islamabad', ranking: 5, feePerYear: 'PKR 210,000', hasScholarship: true, admissionTest: 'NU Test', website: 'https://nu.edu.pk' },
      { name: 'Institute of Business Administration (IBA PU)', location: 'Lahore', ranking: 6, feePerYear: 'PKR 65,000', hasScholarship: true, admissionTest: 'PU Test', website: 'https://ibapu.edu.pk' },
    ],
    careerOutcomes: ['Management Trainee Officer (MTO)', 'Brand Manager', 'Corporate Strategy Associate', 'HR Business Partner', 'Operations Manager', 'Startup Founder'],
    expectedSalary: 'PKR 80,000 - 300,000/month',
    jobMarket: 'excellent',
    idealInterestAreas: ['Business', 'Finance', 'Education'],
    idealActivities: ['Leadership', 'Communication', 'Problem Solving'],
    idealAnalytical: 'medium',
    idealCreativity: 'high',
    workType: 'both',
    successRate: 89,
    averageRating: 4.7,
    isActive: true,
  },
  {
    name: 'BS Accounting & Finance',
    shortName: 'BSAF',
    level: 'bachelor',
    targetAudience: ['intermediate', 'icom', 'ics', 'fsc', 'alevel'],
    institutionType: 'Business Schools & DAIs',
    field: 'Business',
    description: 'Corporate accounting, financial audit, investment valuation, portfolio management, tax law, and capital markets.',
    duration: '4 years',
    requiredSubjects: ['Accounting', 'Mathematics', 'Economics'],
    requiredStream: ['commerce', 'science', 'arts', 'any'],
    minGPA: 2.5,
    universities: [
      { name: 'LUMS (SDSB)', location: 'Lahore', ranking: 1, feePerYear: 'PKR 850,000', hasScholarship: true, admissionTest: 'SAT / LCAT', website: 'https://lums.edu.pk' },
      { name: 'IBA Karachi', location: 'Karachi', ranking: 2, feePerYear: 'PKR 550,000', hasScholarship: true, admissionTest: 'IBA Test', website: 'https://iba.edu.pk' },
      { name: 'Lahore School of Economics (LSE)', location: 'Lahore', ranking: 3, feePerYear: 'PKR 480,000', hasScholarship: true, admissionTest: 'LSE Test', website: 'https://lahoreschoolofeconomics.edu.pk' },
      { name: 'NUST (NBS)', location: 'Islamabad', ranking: 4, feePerYear: 'PKR 240,000', hasScholarship: true, admissionTest: 'NET', website: 'https://nust.edu.pk' },
      { name: 'Hailey College of Banking & Finance (PU)', location: 'Lahore', ranking: 5, feePerYear: 'PKR 50,000', hasScholarship: true, admissionTest: 'PU Test', website: 'https://pu.edu.pk' },
    ],
    careerOutcomes: ['Financial Analyst', 'Investment Banker', 'Audit Senior (Big 4)', 'Risk Manager', 'Tax Consultant', 'CFO Track'],
    expectedSalary: 'PKR 85,000 - 320,000/month',
    jobMarket: 'excellent',
    idealInterestAreas: ['Finance', 'Business'],
    idealActivities: ['Data Analysis', 'Problem Solving', 'Leadership'],
    idealAnalytical: 'high',
    idealCreativity: 'low',
    workType: 'both',
    successRate: 88,
    averageRating: 4.7,
    isActive: true,
  },
  {
    name: 'BS Financial Technology (Fintech)',
    shortName: 'BSFT',
    level: 'bachelor',
    targetAudience: ['intermediate', 'ics', 'icom', 'fsc', 'alevel'],
    institutionType: 'Tech & Business Universities',
    field: 'Business',
    description: 'Modern fusion of blockchain, decentralized finance, algorithmic trading, payment gateways, and banking software.',
    duration: '4 years',
    requiredSubjects: ['Mathematics', 'Computer', 'Economics'],
    requiredStream: ['commerce', 'technology', 'science', 'ics'],
    minGPA: 2.6,
    universities: [
      { name: 'FAST-NUCES', location: 'Islamabad / Lahore', ranking: 1, feePerYear: 'PKR 220,000', hasScholarship: true, admissionTest: 'NU Test', website: 'https://nu.edu.pk' },
      { name: 'Information Technology University (ITU)', location: 'Lahore', ranking: 2, feePerYear: 'PKR 210,000', hasScholarship: true, admissionTest: 'ITU Test', website: 'https://itu.edu.pk' },
      { name: 'NUST (NBS)', location: 'Islamabad', ranking: 3, feePerYear: 'PKR 240,000', hasScholarship: true, admissionTest: 'NET', website: 'https://nust.edu.pk' },
      { name: 'UMT', location: 'Lahore', ranking: 4, feePerYear: 'PKR 230,000', hasScholarship: true, admissionTest: 'UMT Test', website: 'https://umt.edu.pk' },
    ],
    careerOutcomes: ['Fintech Product Specialist', 'Blockchain Developer', 'Payment Gateway Analyst', 'Algorithmic Trader', 'Digital Banking Lead'],
    expectedSalary: 'PKR 100,000 - 380,000/month',
    jobMarket: 'excellent',
    idealInterestAreas: ['Finance', 'Technology', 'Business'],
    idealActivities: ['Problem Solving', 'Data Analysis', 'Building Things'],
    idealAnalytical: 'high',
    idealCreativity: 'medium',
    workType: 'both',
    successRate: 89,
    averageRating: 4.8,
    isActive: true,
  },
  {
    name: 'LLB (Bachelor of Laws - 5 Years)',
    shortName: 'LLB',
    level: 'bachelor',
    targetAudience: ['intermediate', 'fa', 'fsc', 'ics', 'icom', 'alevel'],
    institutionType: 'Law Colleges & Universities (PBC Accredited)',
    field: 'Law',
    description: '5-year professional law curriculum covering constitutional law, criminal jurisprudence, corporate arbitration, civil procedure, and litigation.',
    duration: '5 years',
    requiredSubjects: ['English', 'Pakistan Studies'],
    requiredStream: ['any', 'arts', 'science', 'commerce'],
    minGPA: 2.5,
    universities: [
      { name: 'LUMS (SAHSOL)', location: 'Lahore', ranking: 1, feePerYear: 'PKR 850,000', hasScholarship: true, admissionTest: 'LAT + SAT/LCAT', website: 'https://lums.edu.pk' },
      { name: 'Punjab University Law College (PULC)', location: 'Lahore', ranking: 2, feePerYear: 'PKR 45,000', hasScholarship: true, admissionTest: 'HEC LAT + PU Test', website: 'https://pu.edu.pk' },
      { name: 'Quaid-e-Azam Law College', location: 'Lahore', ranking: 3, feePerYear: 'PKR 160,000', hasScholarship: true, admissionTest: 'LAT', website: 'https://qlc.edu.pk' },
      { name: 'SZABIST Law School', location: 'Karachi / Islamabad', ranking: 4, feePerYear: 'PKR 250,000', hasScholarship: true, admissionTest: 'LAT + Test', website: 'https://szabist.edu.pk' },
      { name: 'The Institute of Legal Studies (TILS)', location: 'Lahore / Islamabad', ranking: 5, feePerYear: 'PKR 380,000', hasScholarship: true, admissionTest: 'LAT / UoL', website: 'https://tils.edu.pk' },
    ],
    careerOutcomes: ['Corporate Legal Counsel', 'Advocate High Court', 'Judicial Civil Judge', 'Arbitration Consultant', 'Human Rights Attorney'],
    expectedSalary: 'PKR 75,000 - 350,000/month',
    jobMarket: 'good',
    idealInterestAreas: ['Law', 'Social Work', 'Business'],
    idealActivities: ['Communication', 'Research', 'Leadership'],
    idealAnalytical: 'high',
    idealCreativity: 'medium',
    workType: 'both',
    successRate: 85,
    averageRating: 4.6,
    isActive: true,
  },
  {
    name: 'BS Clinical Psychology',
    shortName: 'BSPSY',
    level: 'bachelor',
    targetAudience: ['intermediate', 'fa', 'fsc', 'alevel'],
    institutionType: 'Universities & Behavioral Science Institutes',
    field: 'Arts',
    description: 'Cognitive behavioral therapy, psychopathology, developmental psychology, psychometrics, counseling, and neurobiology.',
    duration: '4 years',
    requiredSubjects: ['English', 'Biology'],
    requiredStream: ['any', 'arts', 'science'],
    minGPA: 2.5,
    universities: [
      { name: 'Quaid-e-Azam University (QAU)', location: 'Islamabad', ranking: 1, feePerYear: 'PKR 60,000', hasScholarship: true, admissionTest: 'QAU Test', website: 'https://qau.edu.pk' },
      { name: 'Punjab University (Centre for Clinical Psychology)', location: 'Lahore', ranking: 2, feePerYear: 'PKR 45,000', hasScholarship: true, admissionTest: 'PU Test', website: 'https://pu.edu.pk' },
      { name: 'NUST (S3H)', location: 'Islamabad', ranking: 3, feePerYear: 'PKR 240,000', hasScholarship: true, admissionTest: 'NET', website: 'https://nust.edu.pk' },
      { name: 'GC University (GCU)', location: 'Lahore', ranking: 4, feePerYear: 'PKR 55,000', hasScholarship: true, admissionTest: 'GCU Test', website: 'https://gcu.edu.pk' },
      { name: 'Beaconhouse National University (BNU)', location: 'Lahore', ranking: 5, feePerYear: 'PKR 380,000', hasScholarship: true, admissionTest: 'BNU Test', website: 'https://bnu.edu.pk' },
    ],
    careerOutcomes: ['Clinical Psychologist', 'School Counselor', 'Corporate Wellness Advisor', 'HR Talent Assessment Lead', 'Mental Health Researcher'],
    expectedSalary: 'PKR 65,000 - 240,000/month',
    jobMarket: 'good',
    idealInterestAreas: ['Social Work', 'Healthcare', 'Research'],
    idealActivities: ['Helping People', 'Communication', 'Research'],
    idealAnalytical: 'medium',
    idealCreativity: 'medium',
    workType: 'both',
    successRate: 84,
    averageRating: 4.5,
    isActive: true,
  },
  {
    name: 'BS International Relations & Political Science',
    shortName: 'BSIR',
    level: 'bachelor',
    targetAudience: ['intermediate', 'fa', 'fsc', 'ics', 'icom', 'alevel'],
    institutionType: 'Universities & Social Science Centers',
    field: 'Arts',
    description: 'Foreign policy analysis, global geopolitics, international diplomacy, conflict resolution, security studies, and public administration.',
    duration: '4 years',
    requiredSubjects: ['English', 'Pakistan Studies', 'Sociology'],
    requiredStream: ['any', 'arts', 'humanities', 'commerce', 'science'],
    minGPA: 2.5,
    universities: [
      { name: 'Quaid-e-Azam University (QAU)', location: 'Islamabad', ranking: 1, feePerYear: 'PKR 60,000', hasScholarship: true, admissionTest: 'QAU Test', website: 'https://qau.edu.pk' },
      { name: 'NUST (S3H)', location: 'Islamabad', ranking: 2, feePerYear: 'PKR 240,000', hasScholarship: true, admissionTest: 'NET', website: 'https://nust.edu.pk' },
      { name: 'Kinnaird College for Women', location: 'Lahore', ranking: 3, feePerYear: 'PKR 140,000', hasScholarship: true, admissionTest: 'KC Test', website: 'https://kinnaird.edu.pk' },
      { name: 'GC University (GCU)', location: 'Lahore', ranking: 4, feePerYear: 'PKR 55,000', hasScholarship: true, admissionTest: 'GCU Test', website: 'https://gcu.edu.pk' },
    ],
    careerOutcomes: ['Foreign Service Officer (CSS)', 'Policy Analyst (Think Tanks)', 'UN / NGO Diplomatic Officer', 'Geopolitical Risk Analyst', 'Political Journalist'],
    expectedSalary: 'PKR 70,000 - 280,000/month',
    jobMarket: 'good',
    idealInterestAreas: ['Social Work', 'Law', 'Research'],
    idealActivities: ['Communication', 'Research', 'Leadership'],
    idealAnalytical: 'high',
    idealCreativity: 'medium',
    workType: 'both',
    successRate: 86,
    averageRating: 4.6,
    isActive: true,
  },
  {
    name: 'B.Arch (Bachelor of Architecture - 5 Years)',
    shortName: 'BArch',
    level: 'bachelor',
    targetAudience: ['intermediate', 'fsc', 'ics', 'dae', 'alevel'],
    institutionType: 'Architecture & Design Colleges (PCATP Accredited)',
    field: 'Arts',
    description: '5-year professional architectural studio design, urban planning, sustainability, structural modeling, and 3D parametric visualization.',
    duration: '5 years',
    requiredSubjects: ['Mathematics', 'Physics', 'Art'],
    requiredStream: ['science', 'pre-engineering', 'arts', 'dae'],
    minGPA: 2.7,
    universities: [
      { name: 'National College of Arts (NCA)', location: 'Lahore / Rawalpindi', ranking: 1, feePerYear: 'PKR 85,000', hasScholarship: true, admissionTest: 'NCA Studio Aptitude Test', website: 'https://nca.edu.pk' },
      { name: 'Indus Valley School of Art and Architecture (IVS)', location: 'Karachi', ranking: 2, feePerYear: 'PKR 450,000', hasScholarship: true, admissionTest: 'IVS Drawing Test', website: 'https://indusvalley.edu.pk' },
      { name: 'NUST (SADA)', location: 'Islamabad', ranking: 3, feePerYear: 'PKR 240,000', hasScholarship: true, admissionTest: 'NET + Studio Test', website: 'https://nust.edu.pk' },
      { name: 'COMSATS Architecture Department', location: 'Islamabad / Lahore', ranking: 4, feePerYear: 'PKR 180,000', hasScholarship: true, admissionTest: 'NTS + Creative Test', website: 'https://comsats.edu.pk' },
      { name: 'Beaconhouse National University (BNU)', location: 'Lahore', ranking: 5, feePerYear: 'PKR 420,000', hasScholarship: true, admissionTest: 'BNU Test', website: 'https://bnu.edu.pk' },
    ],
    careerOutcomes: ['Principal Architect', 'Urban Designer', 'Interior Design Lead', 'Landscape Architect', 'BIM Project Manager'],
    expectedSalary: 'PKR 75,000 - 320,000/month',
    jobMarket: 'good',
    idealInterestAreas: ['Architecture', 'Arts & Media', 'Engineering'],
    idealActivities: ['Building Things', 'Creativity', 'Problem Solving'],
    idealAnalytical: 'high',
    idealCreativity: 'high',
    workType: 'practical',
    successRate: 85,
    averageRating: 4.7,
    isActive: true,
  },
  {
    name: 'BS Graphic & Digital Design',
    shortName: 'BSGD',
    level: 'bachelor',
    targetAudience: ['intermediate', 'fa', 'ics', 'icom', 'fsc', 'alevel'],
    institutionType: 'Art & Design Institutes',
    field: 'Arts',
    description: 'Visual branding, UI/UX interaction design, motion graphics, 3D animation, game art, and creative advertising.',
    duration: '4 years',
    requiredSubjects: ['Art', 'Computer', 'English'],
    requiredStream: ['any', 'arts', 'technology', 'commerce'],
    minGPA: 2.2,
    universities: [
      { name: 'National College of Arts (NCA)', location: 'Lahore', ranking: 1, feePerYear: 'PKR 85,000', hasScholarship: true, admissionTest: 'NCA Drawing Test', website: 'https://nca.edu.pk' },
      { name: 'Indus Valley School (IVS)', location: 'Karachi', ranking: 2, feePerYear: 'PKR 450,000', hasScholarship: true, admissionTest: 'IVS Aptitude Test', website: 'https://indusvalley.edu.pk' },
      { name: 'Beaconhouse National University (BNU)', location: 'Lahore', ranking: 3, feePerYear: 'PKR 390,000', hasScholarship: true, admissionTest: 'BNU Test', website: 'https://bnu.edu.pk' },
      { name: 'Pakistan Institute of Fashion and Design (PIFD)', location: 'Lahore', ranking: 4, feePerYear: 'PKR 170,000', hasScholarship: true, admissionTest: 'PIFD Test', website: 'https://pifd.edu.pk' },
    ],
    careerOutcomes: ['Senior UI/UX Product Designer', 'Creative Brand Director', 'Motion Graphics Animator', 'Game Artist', 'Design Lead at Tech SaaS'],
    expectedSalary: 'PKR 80,000 - 350,000/month',
    jobMarket: 'excellent',
    idealInterestAreas: ['Arts & Media', 'Technology'],
    idealActivities: ['Creativity', 'Building Things', 'Problem Solving'],
    idealAnalytical: 'medium',
    idealCreativity: 'high',
    workType: 'practical',
    successRate: 88,
    averageRating: 4.8,
    isActive: true,
  },
  {
    name: 'BS Biotechnology',
    shortName: 'BSBT',
    level: 'bachelor',
    targetAudience: ['intermediate', 'fsc', 'alevel'],
    institutionType: 'Universities & Biological Research Institutes',
    field: 'Medical',
    description: 'Recombinant DNA technology, genetic engineering, bioinformatics, vaccine development, and agricultural bioprocessing.',
    duration: '4 years',
    requiredSubjects: ['Biology', 'Chemistry', 'Physics'],
    requiredStream: ['science', 'pre-medical'],
    minGPA: 2.5,
    universities: [
      { name: 'Quaid-e-Azam University (QAU)', location: 'Islamabad', ranking: 1, feePerYear: 'PKR 60,000', hasScholarship: true, admissionTest: 'QAU Test', website: 'https://qau.edu.pk' },
      { name: 'NUST (ASAB)', location: 'Islamabad', ranking: 2, feePerYear: 'PKR 240,000', hasScholarship: true, admissionTest: 'NET', website: 'https://nust.edu.pk' },
      { name: 'Forman Christian College (FCCU)', location: 'Lahore', ranking: 3, feePerYear: 'PKR 260,000', hasScholarship: true, admissionTest: 'FEAT', website: 'https://fccollege.edu.pk' },
      { name: 'Punjab University (CAMB / MMG)', location: 'Lahore', ranking: 4, feePerYear: 'PKR 45,000', hasScholarship: true, admissionTest: 'PU Test', website: 'https://pu.edu.pk' },
    ],
    careerOutcomes: ['Biotechnologist', 'Bioinformatics Scientist', 'Pharmaceutical R&D Analyst', 'Genetics Researcher', 'Quality Assurance Microbiologist'],
    expectedSalary: 'PKR 65,000 - 240,000/month',
    jobMarket: 'good',
    idealInterestAreas: ['Healthcare', 'Research', 'Environment'],
    idealActivities: ['Research', 'Problem Solving', 'Data Analysis'],
    idealAnalytical: 'high',
    idealCreativity: 'medium',
    workType: 'both',
    successRate: 83,
    averageRating: 4.5,
    isActive: true,
  },
  {
    name: 'BSc (Hons) Agriculture & Agronomy',
    shortName: 'BSAGRI',
    level: 'bachelor',
    targetAudience: ['intermediate', 'fsc', 'dae', 'alevel'],
    institutionType: 'Agricultural Universities',
    field: 'Engineering',
    description: 'Smart precision farming, soil science, crop genetics, agricultural economics, water resource management, and food security.',
    duration: '4 years',
    requiredSubjects: ['Biology', 'Chemistry', 'Mathematics'],
    requiredStream: ['science', 'pre-medical', 'pre-engineering'],
    minGPA: 2.3,
    universities: [
      { name: 'University of Agriculture Faisalabad (UAF)', location: 'Faisalabad', ranking: 1, feePerYear: 'PKR 45,000', hasScholarship: true, admissionTest: 'UAF Entry Test', website: 'https://uaf.edu.pk' },
      { name: 'PMAS Arid Agriculture University', location: 'Rawalpindi', ranking: 2, feePerYear: 'PKR 50,000', hasScholarship: true, admissionTest: 'Arid Test', website: 'https://uaar.edu.pk' },
      { name: 'Sindh Agriculture University', location: 'Tandojam, Sindh', ranking: 3, feePerYear: 'PKR 35,000', hasScholarship: true, admissionTest: 'SAU Test', website: 'https://sau.edu.pk' },
    ],
    careerOutcomes: ['Agricultural Consultant', 'Agronomist Specialist', 'Farm Operations Manager', 'Agri-Tech Startup Lead', 'Food Security Officer'],
    expectedSalary: 'PKR 60,000 - 220,000/month',
    jobMarket: 'good',
    idealInterestAreas: ['Environment', 'Research', 'Business'],
    idealActivities: ['Fieldwork', 'Research', 'Helping People'],
    idealAnalytical: 'medium',
    idealCreativity: 'medium',
    workType: 'practical',
    successRate: 82,
    averageRating: 4.4,
    isActive: true,
  },
]

const seedDegrees = async () => {
  try {
    const mongoUri = process.env.MONGO_URI
    if (!mongoUri) {
      throw new Error('MONGO_URI is missing in environment variables')
    }

    await mongoose.connect(mongoUri)
    logger.info('Seed degrees connected to MongoDB Atlas')

    for (const degreeData of degrees) {
      await Degree.findOneAndUpdate(
        { name: degreeData.name },
        degreeData,
        { upsert: true, returnDocument: 'after', setDefaultsOnInsert: true },
      )
    }

    logger.info(`Successfully seeded ${degrees.length} multi-tier academic programs (Matric Intermediate 2-yr, DAE 3-yr, Bachelor 4/5-yr, Lateral ADP 2-yr, Master 2-yr) with verified institutional data`)
    process.exit(0)
  } catch (err) {
    logger.error('Error seeding degrees', { error: err.message, stack: err.stack })
    process.exit(1)
  }
}

seedDegrees()
